### ISSUE TITLE
Can't build YandexMobileAds for iOS

### ISSUE THREAD

**Issue by osov** [defold/extender#575]
IOS build failed.
Defold 1.9.5
on previous versions of Defold the assembly worked. (pod 'YandexMobileAds', '6.1.0')
In the current version, no option works.

[url extensoin](https://github.com/osov/defold-yandex-easy-monetization)

PodFile (in extension)
```
platform :ios, '13.0'
pod 'YandexMobileAds', '7.2.0' # this option also doesn't work: pod 'YandexMobileAds'
```

ext.manifest (in extension)
```
name: "YandexSdkAds"

platforms:
    android:
        context:
            aaptExtraPackages: ['com.yandex.android', 'com.yandex.android.mobileads', 'com.yandex.mobile', 'com.yandex.mobile.ads', 'com.yandex.mobile.ads.imp', 'androidx.viewpager2', 'androidx.annotation', 'androidx.core', 'androidx.recyclerview', 'androidx.appcompat', 'androidx.transition', 'androidx.collection', 'androidx.appcompat.resources']

    ios:
        context:
            flags: ['-fcxx-modules', '-fmodules', '-fobjc-weak', '-Wno-module-import-in-extern-c']
            linkFlags:  ['-ObjC', '-Wl,-rpath,/usr/lib/swift', '-Wl,-rpath,@executable_path/Frameworks']
            libs:       ['swiftCompatibility51', 'swiftCompatibility50']
```
log with buid pod 'YandexMobileAds', '7.2.0':
[YandexMobileAds-7.2.0.txt](https://github.com/user-attachments/files/18135037/YandexMobileAds-7.2.0.txt)

log with buid pod 'YandexMobileAds':
[YandexMobileAds.txt](https://github.com/user-attachments/files/18135038/YandexMobileAds.txt)

related: [403](https://github.com/defold/extender/issues/403)
