### ISSUE TITLE
Can't build YandexMobileAds for iOS

### ISSUE THREAD

**Issue by osov** [defold/extender#653]
The extension for iOS stopped building.
Defold 1.9.6 built a couple of weeks ago, now it doesn't.
Defold 1.9.7 also fails to build

Errors:
```
upload/extension-yandex-ads/src/extension_ios.mm:35:2: error: cannot find protocol declaration for 'YMAAdViewDelegate'; did you mean 'UIWebViewDelegate'?
        YMAAdViewDelegate,
        ^~~~~~~~~~~~~~~~~
        UIWebViewDelegate
/Users/bjorn/extender-production/platformsdk/iPhoneOS18.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIWebView.h:92:11: note: 'UIWebViewDelegate' declared here
@protocol UIWebViewDelegate <NSObject>
          ^
upload/extension-yandex-ads/src/extension_ios.mm:36:2: error: cannot find protocol declaration for 'YMAInterstitialAdLoaderDelegate'
        YMAInterstitialAdLoaderDelegate,
        ^
upload/extension-yandex-ads/src/extension_ios.mm:41:19: error: unknown type name 'YMAAdView'
@property(strong) YMAAdView *adView;
                  ^
upload/extension-yandex-ads/src/extension_ios.mm:41:1: error: property with 'retain (or strong)' attribute must be of object type
@property(strong) YMAAdView *adView;
^
upload/extension-yandex-ads/src/extension_ios.mm:42:19: error: unknown type name 'YMAInterstitialAd'
@property(strong) YMAInterstitialAd *interstitialAd;
                  ^
upload/extension-yandex-ads/src/extension_ios.mm:42:1: error: property with 'retain (or strong)' attribute must be of object type
@property(strong) YMAInterstitialAd *interstitialAd;
^
upload/extension-yandex-ads/src/extension_ios.mm:43:19: error: unknown type name 'YMARewardedAd'
@property(strong) YMARewardedAd *rewardedAd;
                  ^
upload/extension-yandex-ads/src/extension_ios.mm:43:1: error: property with 'retain (or strong)' attribute must be of object type
@property(strong) YMARewardedAd *rewardedAd;
^
upload/extension-yandex-ads/src/extension_ios.mm:44:19: error: unknown type name 'YMAInterstitialAdLoader'
@property(strong) YMAInterstitialAdLoader *interstitialAdLoader;
                  ^
upload/extension-yandex-ads/src/extension_ios.mm:44:1: error: property with 'retain (or strong)' attribute must be of object type
@property(strong) YMAInterstitialAdLoader *interstitialAdLoader;
^
upload/extension-yandex-ads/src/extension_ios.mm:45:19: error: unknown type name 'YMARewardedAdLoader'
@property(strong) YMARewardedAdLoader *rewardedAdLoader;
                  ^
upload/extension-yandex-ads/src/extension_ios.mm:45:1: error: property with 'retain (or strong)' attribute must be of object type
@property(strong) YMARewardedAdLoader *rewardedAdLoader;
^
upload/extension-yandex-ads/src/extension_ios.mm:183:31: error: expected a type
-(void)adViewDidLoad:(nonnull YMAAdView *)adView {
                              ^
upload/extension-yandex-ads/src/extension_ios.mm:188:38: error: expected a type
-(void)adViewDidFailLoading:(nonnull YMAAdView *)adView error:(nonnull NSError *)error {
                                     ^
upload/extension-yandex-ads/src/extension_ios.mm:192:32: error: expected a type
-(void)adViewDidClick:(nonnull YMAAdView *)adView {
                               ^
upload/extension-yandex-ads/src/extension_ios.mm:208:24: error: expected a type
-(void)adView:(nonnull YMAAdView *)adView didTrackImpressionWithData:(nullable id<YMAImpressionData>)impressionData {
                       ^
upload/extension-yandex-ads/src/extension_ios.mm:208:83: error: no type or protocol named 'YMAImpressionData'
-(void)adView:(nonnull YMAAdView *)adView didTrackImpressionWithData:(nullable id<YMAImpressionData>)impressionData {
                                                                                  ^
upload/extension-yandex-ads/src/extension_ios.mm:215:38: error: expected a type
-(void)interstitialAdLoader:(nonnull YMAInterstitialAdLoader *)adLoader
                                     ^
upload/extension-yandex-ads/src/extension_ios.mm:216:18: error: expected a type
didLoad:(nonnull YMAInterstitialAd *)interstitialAd {
                 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```
Podfile
```
platform :ios, '13.0'
pod 'YandexMobileAds', '7.8.0'
```

ext.manifest:
```
name: "YandexSdkAds"

platforms:
    android:
        context:
            aaptExtraPackages: ['com.yandex.android', 'com.yandex.android.mobileads', 'com.yandex.mobile', 'com.yandex.mobile.ads', 'com.yandex.mobile.ads.imp', 'androidx.viewpager2', 'androidx.annotation', 'androidx.core', 'androidx.recyclerview', 'androidx.appcompat', 'androidx.transition', 'androidx.collection', 'androidx.appcompat.resources']

    ios:
        context:
            flags: ['-fcxx-modules', '-fmodules', '-fobjc-weak', '-Wno-module-import-in-extern-c']
            linkFlags:  ['-ObjC', '-Wl,-rpath,/usr/lib/swift', '-Wl,-rpath,@executable_path/Frameworks']
            libs:       ['swiftCompatibility51', 'swiftCompatibility50']
```

[log.zip](https://github.com/user-attachments/files/18687907/log.zip)

[defold-yandex-easy-monetization.zip](https://github.com/user-attachments/files/18687920/defold-yandex-easy-monetization.zip)
